### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by sam9306**

### CODE REVIEW

**Comment by sam9306** [comment]
git commit -a

**Comment by sam9306** [comment]
git commit --amend --author "Author <email@address.com>"

**Comment by sam9306** [comment]
git commit --amend --author "Spencer McGillicuddy <spencer.the.bestest@gmail.com>"

**Comment by sam9306** [comment]
git commit

**Comment by sam9306** [comment]
git commit --amend --author  sam93062180@gmail.com

**Comment by sam9306** [comment]
[vendor_aosp-twelve-plus.zip](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/10834384/vendor_aosp-twelve-plus.zip)

**Review by nullptr-t-oss — APPROVED** [review]

**Comment by MartinX3** [comment]
Closed as spam.

**Pull request closed without merging**
