### PR TITLE
manifest: Clean up

### PR DESCRIPTION
**Pull request by AndroiableDroid**

### CODE REVIEW

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by ratchanonsuttawas — CHANGES_REQUESTED** [review]
af135e989c249019e785c612278475dbe83f47d6

**Comment by ratchanonsuttawas** [comment]
af135e989c249019e785c612278475dbe83f47d6

**Comment by ratchanonsuttawas** [comment]
>manifest : clean up af135e989c249019e785c612278475dbe83f47d6

**Review by ratchanonsuttawas — COMMENTED** [review]
Manifest : clean up

**Review by ratchanonsuttawas — APPROVED** [review]

**Comment by MartinX3** [comment]
I'm locking this PR because of the 3rd party SPAM.
@AndroiableDroid just reach me out if I need to unlock it for you.

**Pull request merged**
